inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3

Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
